---
title: "3. Complete analysis Eallonardo et al."
author: "Jelyn Gerkema"
date: "2023-06-20"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## 0. Set up
```{r set up}
source("src/settings2.R")
source("src/functions.R")

```

## 1.Clean data


### 1.1 Aiello-Lammens 
```{r clean data}
# The Aiello-lammens dataset contains 2 years. The first vegetation survey was done in 1992. The second one in 2011. In 2011, they did two plots per location to account for differences caused by slight differences in the location. I will analyse the data separately. 

aiello <- read_csv("data/raw/Aiello-Lammens et al. 2016/baviaanskloof_data_dryad.csv") %>%
  filter(Survey == "2011a") %>%
  rename(Name = Species, Plot_code = Plot,  cover = PercCover,
         Height = Height.Mean, LMA = LMA.Mean, Thickness = LeafThickness.Mean,
         LWR = LWR.Mean, FWC = FWC.Mean, FWC = FWC.Mean, twFWC = twFWC.Mean,
         Width = LeafWidthMax.Mean) %>%
  mutate(Name = recode(Name, "Erica newdigateae" = "Erica newdigatei",
                       "Hypodiscus albo-aristatus" = "Hypodiscus alboaristatus",
                       "Pegolettia baccaridifolia" = "Pegolettia baccharidifolia"))

aiello_veg <- aiello %>%
  select(Name, Plot_code, cover) %>%
  pivot_wider(names_from = Name, values_from = cover) %>%
  replace(is.na(.), 0) %>%
  column_to_rownames(var = "Plot_code") %>%
  select(order(colnames(.)))

#aiello2011_species_list <- colnames(aiello_veg)

aiello_trait <- aiello %>%
  select(Name, resprout_postfire, Height, LMA, Thickness, LWR, FWC,
         twFWC, Width) %>% distinct() %>%
  select(order(colnames(.))) %>%
  relocate(Name) %>%
  arrange(Name) %>%
  drop_na()


aiello_trait_fd <- aiello_trait %>%
  column_to_rownames(var = "Name") 

species_list_fd <- aiello_trait %>% pull(Name)

aiello_veg_fd <- aiello_veg %>%
  select(all_of(species_list_fd))

aiello_trait <- aiello_trait %>%
  mutate(resprout_postfire = recode(resprout_postfire, `0` = 1,
                             `1`  =  2)) %>%
  mutate(across(where(is.numeric), ~ c(scale(., center = F)))) 
  
traitlist <- sort(c( "resprout_postfire", "Height", "LMA", "Thickness", "LWR", 
                     "FWC", "twFWC", "Width"))
cwm_names <- paste0(traitlist, "_cwm")
cwv_names <- paste0(traitlist, "_cwv")

trait_information <- lst(traitlist, cwm_names, cwv_names)

aiello2011_output <- lst(input_veg = aiello_veg, 
                         input_veg_fd = aiello_veg_fd,
                         input_trait = aiello_trait,
                         input_trait_fd = aiello_trait_fd,
                         cutoff_value = 0.8,
                         trait_detail = "Study",
                         trait_information = trait_information,
                         study_name = "Aiello1992")

save(aiello2011_output,
 file = "data/processed/aiello2011_prep.RData")

``` 


