---
title: "3. Complete analysis Kassaw et al."
author: "Jelyn Gerkema"
date: "2023-10-16"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## 0. Set up
```{r set up}
source("src/settings2.R")
source("src/functions.R")

```

## 1.Clean data


### 1.1 
```{r clean data}

jager_trait <- read_csv("data/raw/Jager et al. 2014/speciestraits.csv")

species_list <- read_excel("data/raw/Jager et al. 2014/speciescode_list.xlsx")


jager_veg <- read_csv("data/raw/Jager et al. 2014/speciesbasalarea.csv") %>%
  pivot_longer(cols = 2:ncol(.), values_to = "BA", names_to = "species") %>%
  full_join(species_list) %>%
  select(-c(species)) %>%
  pivot_wider(values_from = BA, names_from = Name) %>%
  column_to_rownames(var = "plot") %>%
  select(order(colnames(.)))

jager_trait <- jager_trait %>%
  full_join(species_list) %>%
  rename(LT = leafthick, SLA = sla, LDMC = ldmc, WD = wood, Height = height, 
         SM = `seed mass`, BT = bark, relBT = `relative bark thickness`) %>%
  select(-c(species)) %>%
  mutate(BT = BT + 0.00001,
         relBT = BT + 0.0001) %>%
  select(order(colnames(.))) %>%
  relocate(Name) %>%
  arrange(Name)

jager_trait_fd <- jager_trait %>%
  column_to_rownames(var = "Name") 

jager_trait <- jager_trait %>%
  mutate(across(where(is.numeric), ~ c(scale(., center = F))))  

jager_species_list <- colnames(jager_veg)

traitlist <- sort(c("LT", "BT", "SLA", "leafden", "LDMC", "tdmc", "WD", "relBT", 
                    "leafn", "leafp", "littern", "litterp", "Height", "SM"))
cwm_names <- paste0(traitlist, "_cwm")
cwv_names <- paste0(traitlist, "_cwv")

trait_information <- lst(traitlist, cwm_names, cwv_names)

jager_output <- lst(input_veg = jager_veg, 
                     input_veg_fd = jager_veg,
                     input_trait = jager_trait,
                     input_trait_fd = jager_trait_fd,
                     cutoff_value = 0.8,
                     trait_detail = "Study",
                     trait_information = trait_information,
                     study_name = "Jager")

save(jager_output,
 file = "data/processed/jager_prep.RData")

``` 


